language: python

python:
  - 2.7
  # - 3.3
  # - 3.4

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

# install:
#   # Install conda
#   - sudo pip install conda
#   # install deps
#   - sudo conda init
#   - sudo conda update conda
#   - deps='pip numpy pandas scipy matplotlib'
#   - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
#   - export PATH=$HOME/py/bin:$PATH
#   # install your own package into the environment
#   - python setup.py install

# script:
    # - coverage run --source=epys setup.py test

# after_success:
    # coveralls
