language: python

python:
  - 2.7
  # - 3.3
  # - 3.4

before_install:
    - pip install --upgrade pip
    - pip install numpy
    - pip install coverage
    - pip install coveralls
    - pip install six

install:
    - pip freeze
    - python setup.py install

script:
    - coverage run --source=epys setup.py test

after_success:
    - coveralls
