language: python

python:
  - 2.7
  # - 3.3
  # - 3.4

before_install:
    - pip install --use-mirrors numpy
    - pip install --use-mirrors coverage
    - pip install --use-mirrors coveralls
    - pip install --use-mirrors six

install:
    - pip freeze
    - python setup.py install

script:
    - coverage run --source=epys setup.py test

after_success:
    - coveralls
