language: python

python:
  - 2.7
  # - 3.3
  # - 3.4

notifications:
  email: false

virtualenv:
  system_site_packages: true

# before_script:
#   - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
#   - chmod +x miniconda.sh
#   - export PATH=/home/travis/miniconda/bin:$PATH
#   - conda install --yes numpy=1.8

before_install:
 - sudo apt-get install -qq python-scipy python-matplotlib
 - sudo apt-get install python-setuptools

install:
  - pip install --upgrade pip
  # - pip install numpy==1.7.0
  - pip install coverage
  - pip install coveralls
  - pip install six
    # install pyspice
    # disabling pyspice for now until we have the new library spicepy
  # - git clone https://github.com/johnnycakes79/PySPICE.git pyspice
  # - cd pyspice
  # - python getspice.py
  # - python setup.py install
  # - cd ../
  - pwd
    # install PyAstronomy
  - git clone https://github.com/sczesla/PyAstronomy.git pyastron
  - cd pyastron
  - python setup.py install
  - cd ../
  - pwd
    # install epys
  - pip freeze
  # - pip install numpy --upgrade
  - pip freeze
  - python setup.py install
  - pip freeze
  # - pip install numpy --upgrade
  - pip freeze

before_script:
  - pip uninstall numpy -y
  - pip install -I numpy==1.8.2

script:
  - python -c 'import numpy; print numpy.version.version'
  - pip freeze
  - python setup.py test
  # - coverage run --source=epys setup.py test

after_success:
  # - coveralls
