language: python

python:
  - 2.7
  # - 3.3
  # - 3.4

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-scipy python-matplotlib
 - sudo apt-get install python-setuptools

install:
  - pip install numpy --upgrade
  - pip install coverage
  - pip install coveralls
  - pip install six
    # install pyspice
  - git clone https://github.com/johnnycakes79/PySPICE.git pyspice
  - cd pyspice
  - python getspice.py
  - python setup.py install
  - cd ../
  - pwd
    # install PyAstronomy
  - git clone https://github.com/sczesla/PyAstronomy.git pyastron
  - cd pyastron
  - python setup.py install
  - cd ../
  - pwd
    # install epys
  - python setup.py install

script:
  - python setup.py test
  # - coverage run --source=epys setup.py test

after_success:
  # - coveralls
