# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6

before_install:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
    - git clone https://github.com/sczesla/PyAstronomy.git
    - cd PyAstronomy
    - python setup.py --with-ext install
    - cd ..

script:
    - coverage run --source=epys setup.py test

after_success:
    coveralls
