language: python

python:
- 2.7

before_install:
- pip install --upgrade pip
- pip install numpy
- pip install coverage
- pip install coveralls
- pip install six

install:
- pip freeze
- python setup.py install
- ls test

script:
- coverage run --source=epys setup.py test

after_success:
- coveralls

notifications:
  slack:
    secure: JGXo9wL/C/6IkXT+lJ8aabsbV15xCerDbKg5V3w2Tb/QdMir4TlEMsEI0UZoa5el8lSEEVvHKNnvjd0643VtoLGGYEC7ZM7N0ye8PU24Qi4TJyDXtWQPM9D1gfYy8ytab6UJsqwcnQfiJjbuV760RDXpeaYA8KWLFsmxQEY5Sns=
